Cenoura_RoR/config/routes.rb
Rails.application.routes.draw do 
  resources :events
  resources :profiles
  resources :projetos
  resources :fluxos

  get 'home/index'
  get 'home_admin/index'
  devise_for :users, path: 'users', controllers: {sessions: "user/sessions", registrations: "user/registrations"}
  devise_for :admins, path: 'admins', controllers: {sessions: "admins/sessions", registrations: "admins/registrations"} 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # Dizer quais as pag alcançadas pelo pelo projeto
  get 'timeline/index'

  # root :to => 'home#index'

  devise_scope :admin do
    authenticated :admin do
       root :to => 'home#index', as: 'authenticated_admin'
       # get 'admins/sign_in'
       resources :projetos, only: [:show]
    end
    # unauthenticated :admin do
    #   root :to => 'user/sessions#new', as: 'unauthenticated_admin'
    # end
  end

  devise_scope :user do
    authenticated :user do
       root :to => 'home#index', as: 'authenticated_user'
       # get 'users/sign_in'
    end
    unauthenticated :user do
        root :to => 'user/sessions#new', as: 'unauthenticated_user'  
    end
  end 
end

Cenoura_RoR/app/models/projeto.rb
class Projeto < ApplicationRecord
end

Cenoura_RoR/app/controllers/projetos_controller.rb
class ProjetosController < ApplicationController
  before_action :set_projeto, only: [:show, :edit, :update, :destroy]

  # GET /projetos
  # GET /projetos.json
  def index
    @projetos = Projeto.all
  end

  # GET /projetos/1
  # GET /projetos/1.json
  def show
  end

  # GET /projetos/new
  def new
    @projeto = Projeto.new
  end

  # GET /projetos/1/edit
  def edit
  end

  # POST /projetos
  # POST /projetos.json
  def create
    @projeto = Projeto.new(projeto_params)

    respond_to do |format|
      if @projeto.save
        format.html { redirect_to @projeto, notice: 'Projeto was successfully created.' }
        format.json { render :show, status: :created, location: @projeto }
      else
        format.html { render :new }
        format.json { render json: @projeto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projetos/1
  # PATCH/PUT /projetos/1.json
  def update
    respond_to do |format|
      if @projeto.update(projeto_params)
        format.html { redirect_to @projeto, notice: 'Projeto was successfully updated.' }
        format.json { render :show, status: :ok, location: @projeto }
      else
        format.html { render :edit }
        format.json { render json: @projeto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projetos/1
  # DELETE /projetos/1.json
  def destroy
    @projeto.destroy
    respond_to do |format|
      format.html { redirect_to projetos_url, notice: 'Projeto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_projeto
      @projeto = Projeto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def projeto_params
      params.require(:projeto).permit(:project_name, :description, :begin, :end)
    end
end

Cenoura_RoR/app/helpers/projetos_helper.rb
module ProjetosHelper
end

Cenoura_RoR/app/views/projetos/_form.html.erb
<%= form_with(model: projeto, local: true) do |form| %>
  <% if projeto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(projeto.errors.count, "error") %> prohibited this projeto from being saved:</h2>

      <ul>
      <% projeto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :project_name %>
    <%= form.text_field :project_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :begin %>
    <%= form.date_select :begin %>
  </div>

  <div class="field">
    <%= form.label :end %>
    <%= form.date_select :end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Cenoura_RoR/app/views/projetos/edit.html.erb
<h1>Editing Projeto</h1>

<%= render 'form', projeto: @projeto %>

<%= link_to 'Show', @projeto %> |
<%= link_to 'Back', projetos_path %>

Cenoura_RoR/app/views/projetos/index.html.erb
<p id="notice"><%= notice %></p>
<% if admin_signed_in?%>
<h1>Projetos</h1>

<table>
  <thead>
    <tr>
      <th>Project name</th>
      <th>Description</th>
      <th>Begin</th>
      <th>End</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projetos.each do |projeto| %>
      <tr>
        <td><%= projeto.project_name %></td>
        <td><%= projeto.description %></td>
        <td><%= projeto.begin.strftime("%d/%m/%y") %></td>
        <td><%= projeto.end.strftime("%d/%m/%y") %></td>
        <td><%= link_to 'Show', projeto %></td>
        <td><%= link_to 'Edit', edit_projeto_path(projeto) %></td>
        <td><%= link_to 'Destroy', projeto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Projeto', new_projeto_path %>



<% else %> <% if user_signed_in?%>
<h1>Projetos</h1>
<table>
  <thead>
    <tr>
      <th>Project name</th>
      <th>Description</th>
      <th>Begin</th>
      <th>End</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projetos.each do |projeto| %>
      <tr>
        <td><%= projeto.project_name %></td>
        <td><%= projeto.description %></td>
        <td><%= projeto.begin.strftime("%d/%m/%y") %></td>
        <td><%= projeto.end.strftime("%d/%m/%y") %></td>
        <td><%= link_to 'Show', projeto %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>



<% end %>

Cenoura_RoR/app/views/projetos/new.html.erb
<h1>New Projeto</h1>

<%= render 'form', projeto: @projeto %>

<%= link_to 'Back', projetos_path %>

Cenoura_RoR/app/views/projetos/show.html.erb
<p id="notice"><%= notice %></p>
<% if admin_signed_in?%>
<p>
  <strong>Project name:</strong>
  <%= @projeto.project_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @projeto.description %>
</p>

<p>
  <strong>Begin:</strong>
  <%= @projeto.begin.strftime("%d/%m/%y") %>
</p>

<p>
  <strong>End:</strong>
  <%= @projeto.end.strftime("%d/%m/%y") %>
</p>

<%= link_to 'Edit', edit_projeto_path(@projeto) %> |
<%= link_to 'Back', projetos_path %>
<% else %> <% if user_signed_in?%>
<p>
  <strong>Project name:</strong>
  <%= @projeto.project_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @projeto.description %>
</p>

<p>
  <strong>Begin:</strong>
  <%= @projeto.begin.strftime("%d/%m/%y") %>
</p>

<p>
  <strong>End:</strong>
  <%= @projeto.end.strftime("%d/%m/%y") %>
</p>

<%= link_to 'Back', projetos_path %>
<%else%>
<%end%>
<%end%>