Cenoura_RoR/config/routes.rb
Rails.application.routes.draw do 
  resources :events
  resources :profiles
  resources :projetos
  resources :fluxos

  get 'home/index'
  get 'home_admin/index'
  devise_for :users, path: 'users', controllers: {sessions: "user/sessions", registrations: "user/registrations"}
  devise_for :admins, path: 'admins', controllers: {sessions: "admins/sessions", registrations: "admins/registrations"} 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # Dizer quais as pag alcançadas pelo pelo projeto
  get 'timeline/index'

  # root :to => 'home#index'

  devise_scope :admin do
    authenticated :admin do
       root :to => 'home#index', as: 'authenticated_admin'
       # get 'admins/sign_in'
       resources :projetos, only: [:show]
    end
    # unauthenticated :admin do
    #   root :to => 'user/sessions#new', as: 'unauthenticated_admin'
    # end
  end

  devise_scope :user do
    authenticated :user do
       root :to => 'home#index', as: 'authenticated_user'
       # get 'users/sign_in'
    end
    unauthenticated :user do
        root :to => 'user/sessions#new', as: 'unauthenticated_user'  
    end
  end 
end

Cenoura_RoR/app/models/event.rb
class Event < ApplicationRecord
end

Cenoura_RoR/app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :description, :city, :begin_date, :end_date)
    end
end

Cenoura_RoR/app/helpers/events_helper.rb
module EventsHelper
end

Cenoura_RoR/app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :begin_date %>
    <%= form.date_select :begin_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.date_select :end_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Cenoura_RoR/app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

Cenoura_RoR/app/views/events/index.html.erb
<p id="notice"><%= notice %></p>
<% if admin_signed_in?%>
<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>City</th>
      <th>Begin date</th>
      <th>End date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.description %></td>
        <td><%= event.city %></td>
        <td><%= event.begin_date.strftime("%d/%m/%y") %></td>
        <td><%= event.end_date.strftime("%d/%m/%y") %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

<% else %> <% if user_signed_in?%>
  <h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>City</th>
      <th>Begin date</th>
      <th>End date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.description %></td>
        <td><%= event.city %></td>
        <td><%= event.begin_date.strftime("%d/%m/%y") %></td>
        <td><%= event.end_date.strftime("%d/%m/%y") %></td>
        <td><%= link_to 'Show', event %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% else %>
<% end %>
<% end %>

Cenoura_RoR/app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

Cenoura_RoR/app/views/events/show.html.erb
<p id="notice"><%= notice %></p>
<% if admin_signed_in?%>
<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>City:</strong>
  <%= @event.city %>
</p>

<p>
  <strong>Begin date:</strong>
  <%= @event.begin_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @event.end_date %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

<% else %> <% if user_signed_in?%>
<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>City:</strong>
  <%= @event.city %>
</p>

<p>
  <strong>Begin date:</strong>
  <%= @event.begin_date.strftime("%d/%m/%y") %>
</p>

<p>
  <strong>End date:</strong>
  <%= @event.end_date.strftime("%d/%m/%y") %>
</p>

<%= link_to 'Back', events_path %>
<%else%>
<%end%>
<%end%>