Cenoura_RoR/config/routes.rb
Rails.application.routes.draw do 
  resources :events
  resources :profiles
  resources :projetos
  resources :fluxos

  get 'home/index'
  get 'home_admin/index'
  devise_for :users, path: 'users', controllers: {sessions: "user/sessions", registrations: "user/registrations"}
  devise_for :admins, path: 'admins', controllers: {sessions: "admins/sessions", registrations: "admins/registrations"} 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # Dizer quais as pag alcançadas pelo pelo projeto
  get 'timeline/index'

  # root :to => 'home#index'

  devise_scope :admin do
    authenticated :admin do
       root :to => 'home#index', as: 'authenticated_admin'
       # get 'admins/sign_in'
       resources :projetos, only: [:show]
    end
    # unauthenticated :admin do
    #   root :to => 'user/sessions#new', as: 'unauthenticated_admin'
    # end
  end

  devise_scope :user do
    authenticated :user do
       root :to => 'home#index', as: 'authenticated_user'
       # get 'users/sign_in'
    end
    unauthenticated :user do
        root :to => 'user/sessions#new', as: 'unauthenticated_user'  
    end
  end 
end

Cenoura_RoR/app/models/fluxo.rb
class Fluxo < ApplicationRecord
end

Cenoura_RoR/app/controllers/fluxos_controller.rb
class FluxosController < ApplicationController
  before_action :set_fluxo, only: [:show, :edit, :update, :destroy]

  # GET /fluxos
  # GET /fluxos.json
  def index
    @fluxos = Fluxo.all
  end

  # GET /fluxos/1
  # GET /fluxos/1.json
  def show
  end

  # GET /fluxos/new
  def new
    @fluxo = Fluxo.new
  end

  # GET /fluxos/1/edit
  def edit
  end

  # POST /fluxos
  # POST /fluxos.json
  def create
    @fluxo = Fluxo.new(fluxo_params)

    respond_to do |format|
      if @fluxo.save
        format.html { redirect_to @fluxo, notice: 'Fluxo was successfully created.' }
        format.json { render :show, status: :created, location: @fluxo }
      else
        format.html { render :new }
        format.json { render json: @fluxo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fluxos/1
  # PATCH/PUT /fluxos/1.json
  def update
    respond_to do |format|
      if @fluxo.update(fluxo_params)
        format.html { redirect_to @fluxo, notice: 'Fluxo was successfully updated.' }
        format.json { render :show, status: :ok, location: @fluxo }
      else
        format.html { render :edit }
        format.json { render json: @fluxo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fluxos/1
  # DELETE /fluxos/1.json
  def destroy
    @fluxo.destroy
    respond_to do |format|
      format.html { redirect_to fluxos_url, notice: 'Fluxo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fluxo
      @fluxo = Fluxo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fluxo_params
      params.require(:fluxo).permit(:money, :description, :user, :day)
    end
end

Cenoura_RoR/app/helpers/fluxos_helper.rb
module FluxosHelper
end

Cenoura_RoR/app/views/fluxos/_form.html.erb
<%= form_with(model: fluxo, local: true) do |form| %>
  <% if fluxo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fluxo.errors.count, "error") %> prohibited this fluxo from being saved:</h2>

      <ul>
      <% fluxo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :money %>
    <%= form.text_field :money %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :user %>
    <%= form.text_field :user %>
  </div>

  <div class="field">
    <%= form.label :day %>
    <%= form.date_select :day %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Cenoura_RoR/app/views/fluxos/edit.html.erb
<h1>Editing Fluxo</h1>

<%= render 'form', fluxo: @fluxo %>

<%= link_to 'Show', @fluxo %> |
<%= link_to 'Back', fluxos_path %>

Cenoura_RoR/app/views/fluxos/index.html.erb
<p id="notice"><%= notice %></p>
<% if admin_signed_in?%>
<h1>Fluxos</h1>

<table>
  <thead>
    <tr>
      <th>Money</th>
      <th>Description</th>
      <th>User</th>
      <th>Day</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fluxos.each do |fluxo| %>
      <tr>
        <td><%= fluxo.money %></td>
        <td><%= fluxo.description %></td>
        <td><%= fluxo.user %></td>
        <td><%= fluxo.day.strftime("%d/%m/%y") %></td>
        <td><%= link_to 'Show', fluxo %></td>
        <td><%= link_to 'Edit', edit_fluxo_path(fluxo) %></td>
        <td><%= link_to 'Destroy', fluxo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>
<br>
<section>
  <strong>Balanço:</strong>
  <span>R$ <%= @fluxos.sum(:money) %></span>
</section>
<br>

<%= link_to 'New Fluxo', new_fluxo_path %>

<% else %> <% if user_signed_in?%>
<h1>Fluxos</h1>

<table>
  <thead>
    <tr>
      <th>Money</th>
      <th>Description</th>
      <th>User</th>
      <th>Day</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fluxos.each do |fluxo| %>
      <tr>
        <td><%= fluxo.money %></td>
        <td><%= fluxo.description %></td>
        <td><%= fluxo.user %></td>
        <td><%= fluxo.day.strftime("%d/%m/%y") %></td>
        <td><%= link_to 'Show', fluxo %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>
<br>
<section>
  <strong>Balanço:</strong>
  <span>R$ <%= @fluxos.sum(:money) %></span>
</section>
<br>

<% else %> 
<% end %>
<% end %>

Cenoura_RoR/app/views/fluxos/new.html.erb
<h1>New Fluxo</h1>

<%= render 'form', fluxo: @fluxo %>

<%= link_to 'Back', fluxos_path %>

Cenoura_RoR/app/views/fluxos/show.html.erb
<p id="notice"><%= notice %></p>
<% if admin_signed_in?%>
<p>
  <strong>Money:</strong>
  <%= @fluxo.money %>
</p>

<p>
  <strong>Description:</strong>
  <%= @fluxo.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @fluxo.user %>
</p>

<p>
  <strong>Day:</strong>
  <%= @fluxo.day.strftime("%d/%m/%y") %>
</p>

<%= link_to 'Edit', edit_fluxo_path(@fluxo) %> |
<%= link_to 'Back', fluxos_path %>

<% else %> <% if user_signed_in?%>

<p>
  <strong>Money:</strong>
  <%= @fluxo.money %>
</p>

<p>
  <strong>Description:</strong>
  <%= @fluxo.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @fluxo.user %>
</p>

<p>
  <strong>Day:</strong>
  <%= @fluxo.day.strftime("%d/%m/%y") %>
</p>

<%= link_to 'Back', fluxos_path %>
<% else %>
<%end%>
<%end%>