Cenoura_RoR/config/routes.rb
Rails.application.routes.draw do 
  resources :events
  resources :profiles
  resources :projetos
  resources :fluxos

  get 'home/index'
  get 'home_admin/index'
  devise_for :users, path: 'users', controllers: {sessions: "user/sessions", registrations: "user/registrations"}
  devise_for :admins, path: 'admins', controllers: {sessions: "admins/sessions", registrations: "admins/registrations"} 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # Dizer quais as pag alcançadas pelo pelo projeto
  get 'timeline/index'

  # root :to => 'home#index'

  devise_scope :admin do
    authenticated :admin do
       root :to => 'home#index', as: 'authenticated_admin'
       # get 'admins/sign_in'
       resources :projetos, only: [:show]
    end
    # unauthenticated :admin do
    #   root :to => 'user/sessions#new', as: 'unauthenticated_admin'
    # end
  end

  devise_scope :user do
    authenticated :user do
       root :to => 'home#index', as: 'authenticated_user'
       # get 'users/sign_in'
    end
    unauthenticated :user do
        root :to => 'user/sessions#new', as: 'unauthenticated_user'  
    end
  end 
end

Cenoura_RoR/app/controllers/home_controller.rb
class HomeController < ApplicationController
	layout 'admin_lte_2'
  def index
    
  end
end

Cenoura_RoR/app/helpers/home_helper.rb
module HomeHelper
end

Cenoura_RoR/app/views/home/index.html.erb
<center>

<h1>Bem vindo, meu consagrado. Bora impactar?</h1>


<% if admin_signed_in?%>

	<%= link_to 'Deslogar',  destroy_admin_session_path, method: :delete %>
	<br>
	<%= link_to 'Editar',  edit_profile_path(current_admin.id)%>
	<br>
	<%= link_to 'Destroy', admin_registration_path, method: :delete, data: { confirm: 'Are you sure?' } %>
	
<% else %><% if user_signed_in?%>

	<%= link_to 'Deslogar',  destroy_user_session_path, method: :delete %>
	<br>
	<%= link_to 'Editar',  edit_profile_path(current_user.id)%>
	<br>
	<%= link_to 'Destroy', user_registration_path, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>
<% end %>
</center>
<div class = "teste">		
</div>
																																																																							